### ISSUE TITLE
Add export FLASK_APP_CONFIG="config.DevelopmentConfig" to Dev vs Production Configurations guide.

### ISSUE THREAD

**Issue by DanLindeman** [mattfinnell/flask-webpack-cookiecutter#1]
First time users may not be aware that they have to set a `FLASK_APP_CONFIG` environment variable. I see the very next section explains the default as DevelopmentConfig, but when I ran `python wsgi.py`, initially I received:
```
Traceback (most recent call last):
  File "wsgi.py", line 6, in <module>
    config_object = eval(os.environ['FLASK_APP_CONFIG'])
  File "/Users/daniellindeman/.pyenv/versions/3.6.2/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'FLASK_APP_CONFIG'
```

Somehow my environment did not pick up the default (possibly due to my autoenv setup?) so it may be worth mentioning that they'll need to manually set it if this happens.

While we're thinking about this section, I also noticed a typo in
```
Environments can easily be changing between by these environment variables. The build tool defaults to DevelopmentConfig.
```
`changing` should be `changed`.

Love the project, keep it up!

**Comment by mattfinnell** [comment]
@DanLindeman 

> Somehow my environment did not pick up the default (possibly due to my autoenv setup?) 

Hmmm, interesting. I'll try to reproduce this on a VM real quick and get back to you on that. I've just been cloning it into a test directory adjacent to all my other messy projects and just hope it works. Definitely not the cleanest environment. I really wouldn't be surprised if the project was assuming something goofy.

> While we're thinking about this section, I also noticed a typo in ...

Well lookie there. I probably have a bunch hiding around, thanks for the catch!

> Love the project, keep it up!

Many Thanks! I'm very hyped on the support!

**Comment by mattfinnell** [comment]
@DanLindeman 

> Somehow my environment did not pick up the default (possibly due to my autoenv setup?)

I reproduced it. And yeah, it looks exactly like `autoenv` doesn't want to start which prevents both the environment variable from getting set and `virtualenv` to run. I'll fix it when I get the chance.

**Comment by DanLindeman** [comment]
Awesome! Thanks for the feedback on this issue. Really helpful! I'll comb through everything else if you'd like me to, I like this image, and I'm going to try to use it with React, so I'm glad to help!

**Comment by mattfinnell** [comment]
Hey @DanLindeman! Checkout the `fix-env-vars` branch and retry the project. I'm pretty sure I got the issue fixed but would like some extra hands to be sure.

My bad for not addressing the trivial changes earlier. I got distracted with noodling around with my VM stuff that I crafted some new scripts that build my environment. I also got carried away with redoing my whole vim configuration in the process :man_shrugging:.

**Comment by DanLindeman** [comment]
At least the Yak got shaved. I also had some other commitments come up, totally understood. I'll update when I've tried it out!

**Comment by DanLindeman** [comment]
Beautiful! Works perfectly for me. Thanks for the speedy fix!

**Comment by mattfinnell** [comment]
👍
